CREATE DATABASE  wc2026;
USE wc2026;

/* VARCHAR != CHAR:  	
	VARCHAR OCCUPIES ONLY THE NECESSARY E.g: IF VARCHAR(100) IS DEFINED BUT THE NAME ONLY USES 6 CHARACTERS, ONLY 6 BYTES ARE STORED. 
    CHAR OCCUPIES EXACTLY WHAT IS DEFINED E.g: CHAR(1) ALWAYS STORES 1 BYTE, REGARDLESS OF THE CONTENT.
*/

CREATE TABLE selections (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
	group_name CHAR(1) NOT NULL,
    
);

resposta no readme 
